### PR TITLE
Fix readme example (Fixes #5)

### LINKED ISSUE #5: unable to run example
As in http://amol-mandhane.github.io/htmlPy/ , I created three files exactly the same as the example in `hpy_test/`.

Then I ran

```
cd hpy_test
python main.py
```

I got the following error:

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from back_end import BackEnd
  File "hpy_test/back_end.py", line 2, in <module>
    from main import app
  File "hpy_test/main.py", line 2, in <module>
    from back_end import BackEnd
ImportError: cannot import name BackEnd
```

And if I ran

```
# cd hpy_test
python back_end.py
```

I got the following error:

```
Traceback (most recent call last):
  File "back_end.py", line 2, in <module>
    from main import app
  File "hpy_test/main.py", line 2, in <module>
    from back_end import BackEnd
  File "hpy_test/back_end.py", line 2, in <module>
    from main import app
ImportError: cannot import name app
```

I am using python 2.7 (64bit), pyside 1.2.1 and htmlpy 2.0.3 in 64 bit windows 10.

### PR DESCRIPTION
**Pull request by bendtherules**
Changes made [In readme]:
1. Pass app from main.py to back_end.py to maintain singleton app
2. Fix indent in main.py

Fixes #5

### CODE REVIEW

**Comment by cosme12** [comment]
Right, this fix #5 but you end up with a huge mega file. I think the back-end idea was to prevent this.

**Comment by bendtherules** [comment]
I cant see which file has substantially increased size in this edit? They have hardly changed wrt line no. count in any file.

**Comment by cosme12** [comment]
I mean, `BackEnd class` will end up being really big. Maybe that was the idea of importing it from another file. Anyways, this fix is still a good option.

**Comment by bendtherules** [comment]
You could alternatively do `back_end.app_gui=app` from main.py and then it will be available as a global variable within back_end too - but usually you do have a main backend class which responds to different function calls.

Because `back_end.py` needs to access  `app` created in `main.py` and `main.py` will also import `back_end.py` before creating `app`, you need some way for `main.py` to pass on the `app` instance it created to `back_end.py`

**Comment by amol-mandhane** [comment]
I'm still trying to figure out a good pattern for solving this import inconsistency. The one you put in the pull request seems good. I want to see it there's anything else that can be done. If not, I'll merge this one.

PS. The back-end class shouldn't get really big. You can modularize back-end as per the application requirement and bind multiple classes to the GUI.

PPS. I'm not able to put in lot of time on this project because of my day job. Dev on this will be a little slow.

**Comment by afharvey** [comment]
@amol-mandhane Just saw #5 then found this and the example now works. Merge ftw?

**Comment by amol-mandhane** [comment]
Fixed the example.

**Pull request closed without merging**
